---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  # The name will be used to generate the placementBinding and placementRule names as {name}-placementBinding and {name}-placementRule
  name: "group-du-sno"
  namespace: "group-du-sno-policies"
spec:
  bindingRules:
    group-du-sno: ""
  mcp: "master"
  sourceFiles:
    # Set ClusterLogForwarder as example might be better to create another policyTemp-Group
    - fileName: ClusterLogForwarder.yaml
      policyName: "log-forwarder-policy"
      spec:
        outputs:
        - type: "kafka"
          name: kafka-open
          # below url is an example
          kafka:
            url: tcp://10.46.55.190:9092/test
        filters:
        - name: test-labels
          type: openshiftLabels
          openshiftLabels:
            label1: test1
            label2: test2
            label3: test3
            label4: test4
        pipelines:
        - name: all-to-default
          inputRefs:
          - audit
          - infrastructure
          filterRefs:
          - test-labels
          outputRefs:
          - kafka-open
    - fileName: MachineConfigSctp.yaml
      policyName: "mc-sctp-policy"
      metadata:
        labels:
          machineconfiguration.openshift.io/role: master
    - fileName: PtpConfigSlave.yaml
      policyName: "ptp-config-policy"
      metadata:
        name: "du-ptp-slave"
      spec:
        profile:
        - name: "slave"
          interface: "ens5f0"
          ptp4lOpts: "-2 -s --summary_interval -4"
          phc2sysOpts: "-a -r -n 24"
    - fileName: SriovOperatorConfig.yaml
      policyName: "sriov-operconfig-policy"
    - fileName: DisableSnoNetworkDiag.yaml
      policyName: "disable-network-diag"
      metadata:
        labels:
          machineconfiguration.openshift.io/role: master
    # # AmqInstance is required if PTP and BMER operators use AMQP transport
    # - fileName: AmqInstance.yaml
