---
# Example for using the PolicyGenTemplate to create ACM policies with binding rules group-du-sno.
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
 name: "group-du-sno" # policygentemp-example
 namespace: "group-du-sno"
spec:
  bindingRules:
    group-du-sno: ""
  mcp: "master"
  evaluationInterval:
    compliant: 20m
    noncompliant: 15s

  sourceFiles:
    - fileName: ClusterLogForwarding.yaml
      policyName: "log-forwarding-policy"
      evaluationInterval:
        compliant: 30m
      spec:
        outputs:
        - type: "kafka"
          name: kafka-open
          kafka:
            # Example URL only
            url: tcp://192.168.1.2
        filters:
        - name: test-labels
          type: openshiftLabels
          openshiftLabels:
            label1: test1
            label2: test2
            label3: test3
            label4: test4
        pipelines:
        - name: all-to-default
          inputRefs:
          - audit
          - infrastructure
          filterRefs:
          - test-labels
          outputRefs:
          - kafka-open
---
# Example for using the PolicyGenTemplate to create a single ACM policy by repeating the policyName in the
# sourceFiles items.
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
 name: "common" # policygentemp-ex-to-create-single-acm-policy
 namespace: "common"
spec:
  bindingRules:
    common: "true"
  mcp: "master"
  sourceFiles:
    - fileName: PaoSubscription.yaml
      policyName: "pao-sub-policy"
      spec:
      # Changing the channel value will upgrade/downgrade the operator installed version.
        channel: "4.8"
    - fileName: PaoSubscriptionNS.yaml
      policyName: "pao-sub-policy"
    - fileName: PaoSubscriptionOperGroup.yaml
      policyName: "pao-sub-policy"
---
# Example for using the PolicyGenTemplate to create the CR without wrapping it to ACM policy by giving empty policyName
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
 name: "policygentemp-ex-to-create-cr-only"
 namespace: "policy-templates"
spec:
  mcp: "master"
  sourceFiles:
    - fileName: SriovNetworkNodePolicy.yaml
      metadata:
        name: "sriov-nnp-du-mh"
      spec:
        deviceType: vfio-pci
        isRdma: false
        nicSelector:
          pfNames: ["ens7f0"]
        numVfs: 8
        priority: 10
        resourceName: du_mh
